
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import { pgTable, index, uniqueIndex, foreignKey, integer, varchar, serial, timestamp, jsonb, boolean, numeric, pgEnum } from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_jobs_category = pgEnum('enum_jobs_category', ['cong-nghe', 'kinh-doanh', 'marketing', 'van-hanh', 'nhan-su', 'tai-chinh'])
export const enum_jobs_type = pgEnum('enum_jobs_type', ['full-time', 'part-time', 'contract', 'intern'])
export const enum_jobs_tag = pgEnum('enum_jobs_tag', ['Mới', 'Hot', 'Tuyển gấp'])
export const enum_jobs_status = pgEnum('enum_jobs_status', ['active', 'closed'])
export const enum_posts_category = pgEnum('enum_posts_category', ['su-kien', 'cong-nghe', 'van-hoa', 'kinh-doanh', 'van-hanh'])
export const enum_applications_status = pgEnum('enum_applications_status', ['new', 'reviewing', 'accepted', 'rejected'])

export const jobs_requirements = pgTable('jobs_requirements', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  requirement: varchar('requirement').notNull(),
}, (columns) => [
    index('jobs_requirements_order_idx').on(columns._order), index('jobs_requirements_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [jobs.id],
      name: 'jobs_requirements_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const jobs = pgTable('jobs', {
  id: serial('id').primaryKey(),
  title: varchar('title').notNull(),
  slug: varchar('slug'),
  icon: varchar('icon').default("💼"),
  category: enum_jobs_category('category').notNull(),
  location: varchar('location').default("Hà Nội"),
  type: enum_jobs_type('type').default("full-time"),
  level: varchar('level'),
  salary: varchar('salary').notNull(),
  tag: enum_jobs_tag('tag'),
  description: varchar('description').notNull(),
  benefits: varchar('benefits'),
  workingHours: varchar('working_hours').default("Thứ 2 – Thứ 7, Sáng 8h30 – 12h00, Chiều 13h30 – 17h30\nThứ 7 làm việc đến 16h00\nNghỉ 1 Thứ 7 cuối tháng và 4 Chủ nhật, chính thức nghỉ thêm 1 ngày phép"),
  contactEmail: varchar('contact_email').default("hr@bydgroup.vn"),
  status: enum_jobs_status('status').default("active"),
  publishedAt: timestamp('published_at', {mode: 'string',withTimezone: true,precision: 3}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    uniqueIndex('jobs_slug_idx').on(columns.slug), index('jobs_updated_at_idx').on(columns.updatedAt), index('jobs_created_at_idx').on(columns.createdAt),
]
)


export const posts = pgTable('posts', {
  id: serial('id').primaryKey(),
  title: varchar('title').notNull(),
  slug: varchar('slug'),
  category: enum_posts_category('category'),
  excerpt: varchar('excerpt'),
  content: jsonb('content'),
  featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  externalImageUrl: varchar('external_image_url'),
  author: varchar('author'),
  readTime: varchar('read_time'),
  featured: boolean('featured').default(false),
  publishedAt: timestamp('published_at', {mode: 'string',withTimezone: true,precision: 3}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    uniqueIndex('posts_slug_idx').on(columns.slug), index('posts_featured_image_idx').on(columns.featuredImage), index('posts_updated_at_idx').on(columns.updatedAt), index('posts_created_at_idx').on(columns.createdAt),
]
)


export const applications = pgTable('applications', {
  id: serial('id').primaryKey(),
  fullName: varchar('full_name').notNull(),
  email: varchar('email').notNull(),
  phone: varchar('phone').notNull(),
  position: integer('position_id').references(() => jobs.id, {
      onDelete: 'set null'
  }),
  positionText: varchar('position_text'),
  expectedSalary: varchar('expected_salary'),
  cv: integer('cv_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  coverLetter: varchar('cover_letter'),
  status: enum_applications_status('status').default("new"),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('applications_position_idx').on(columns.position), index('applications_cv_idx').on(columns.cv), index('applications_updated_at_idx').on(columns.updatedAt), index('applications_created_at_idx').on(columns.createdAt),
]
)


export const media_variants = pgTable('media_variants', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  name: varchar('name'),
  url: varchar('url'),
  width: numeric('width', {mode: 'number'}),
  height: numeric('height', {mode: 'number'}),
  fileSize: numeric('file_size', {mode: 'number'}),
}, (columns) => [
    index('media_variants_order_idx').on(columns._order), index('media_variants_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [media.id],
      name: 'media_variants_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const media = pgTable('media', {
  id: serial('id').primaryKey(),
  alt: varchar('alt'),
  originalFileSize: numeric('original_file_size', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  url: varchar('url'),
  thumbnailURL: varchar('thumbnail_u_r_l'),
  filename: varchar('filename'),
  mimeType: varchar('mime_type'),
  filesize: numeric('filesize', {mode: 'number'}),
  width: numeric('width', {mode: 'number'}),
  height: numeric('height', {mode: 'number'}),
  focalX: numeric('focal_x', {mode: 'number'}),
  focalY: numeric('focal_y', {mode: 'number'}),
  sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
  sizes_thumbnail_width: numeric('sizes_thumbnail_width', {mode: 'number'}),
  sizes_thumbnail_height: numeric('sizes_thumbnail_height', {mode: 'number'}),
  sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
  sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', {mode: 'number'}),
  sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
  sizes_card_url: varchar('sizes_card_url'),
  sizes_card_width: numeric('sizes_card_width', {mode: 'number'}),
  sizes_card_height: numeric('sizes_card_height', {mode: 'number'}),
  sizes_card_mimeType: varchar('sizes_card_mime_type'),
  sizes_card_filesize: numeric('sizes_card_filesize', {mode: 'number'}),
  sizes_card_filename: varchar('sizes_card_filename'),
  sizes_hero_url: varchar('sizes_hero_url'),
  sizes_hero_width: numeric('sizes_hero_width', {mode: 'number'}),
  sizes_hero_height: numeric('sizes_hero_height', {mode: 'number'}),
  sizes_hero_mimeType: varchar('sizes_hero_mime_type'),
  sizes_hero_filesize: numeric('sizes_hero_filesize', {mode: 'number'}),
  sizes_hero_filename: varchar('sizes_hero_filename'),
}, (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt), index('media_created_at_idx').on(columns.createdAt), uniqueIndex('media_filename_idx').on(columns.filename), index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(columns.sizes_thumbnail_filename), index('media_sizes_card_sizes_card_filename_idx').on(columns.sizes_card_filename), index('media_sizes_hero_sizes_hero_filename_idx').on(columns.sizes_hero_filename),
]
)


export const users_sessions = pgTable('users_sessions', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}),
  expiresAt: timestamp('expires_at', {mode: 'string',withTimezone: true,precision: 3}).notNull(),
}, (columns) => [
    index('users_sessions_order_idx').on(columns._order), index('users_sessions_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  email: varchar('email').notNull(),
  resetPasswordToken: varchar('reset_password_token'),
  resetPasswordExpiration: timestamp('reset_password_expiration', {mode: 'string',withTimezone: true,precision: 3}),
  salt: varchar('salt'),
  hash: varchar('hash'),
  loginAttempts: numeric('login_attempts', {mode: 'number'}).default(0),
  lockUntil: timestamp('lock_until', {mode: 'string',withTimezone: true,precision: 3}),
}, (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt), index('users_created_at_idx').on(columns.createdAt), uniqueIndex('users_email_idx').on(columns.email),
]
)


export const payload_kv = pgTable('payload_kv', {
  id: serial('id').primaryKey(),
  key: varchar('key').notNull(),
  data: jsonb('data').notNull(),
}, (columns) => [
    uniqueIndex('payload_kv_key_idx').on(columns.key),
]
)


export const payload_locked_documents = pgTable('payload_locked_documents', {
  id: serial('id').primaryKey(),
  globalSlug: varchar('global_slug'),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug), index('payload_locked_documents_updated_at_idx').on(columns.updatedAt), index('payload_locked_documents_created_at_idx').on(columns.createdAt),
]
)


export const payload_locked_documents_rels = pgTable('payload_locked_documents_rels', {
  id: serial('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: varchar('path').notNull(),
  jobsID: integer('jobs_id'),
  postsID: integer('posts_id'),
  applicationsID: integer('applications_id'),
  mediaID: integer('media_id'),
  usersID: integer('users_id'),
}, (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order), index('payload_locked_documents_rels_parent_idx').on(columns.parent), index('payload_locked_documents_rels_path_idx').on(columns.path), index('payload_locked_documents_rels_jobs_id_idx').on(columns.jobsID), index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID), index('payload_locked_documents_rels_applications_id_idx').on(columns.applicationsID), index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID), index('payload_locked_documents_rels_users_id_idx').on(columns.usersID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['jobsID']],
      foreignColumns: [jobs.id],
      name: 'payload_locked_documents_rels_jobs_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['applicationsID']],
      foreignColumns: [applications.id],
      name: 'payload_locked_documents_rels_applications_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk'
    }).onDelete('cascade'),
]
)


export const payload_preferences = pgTable('payload_preferences', {
  id: serial('id').primaryKey(),
  key: varchar('key'),
  value: jsonb('value'),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('payload_preferences_key_idx').on(columns.key), index('payload_preferences_updated_at_idx').on(columns.updatedAt), index('payload_preferences_created_at_idx').on(columns.createdAt),
]
)


export const payload_preferences_rels = pgTable('payload_preferences_rels', {
  id: serial('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: varchar('path').notNull(),
  usersID: integer('users_id'),
}, (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order), index('payload_preferences_rels_parent_idx').on(columns.parent), index('payload_preferences_rels_path_idx').on(columns.path), index('payload_preferences_rels_users_id_idx').on(columns.usersID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk'
    }).onDelete('cascade'),
]
)


export const payload_migrations = pgTable('payload_migrations', {
  id: serial('id').primaryKey(),
  name: varchar('name'),
  batch: numeric('batch', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt), index('payload_migrations_created_at_idx').on(columns.createdAt),
]
)

export const relations_jobs_requirements = relations(jobs_requirements, ({ one }) => ({
  _parentID: one(jobs, {
    
    fields: [jobs_requirements._parentID],
    references: [jobs.id],
    relationName: 'requirements',
    }),
      }))
export const relations_jobs = relations(jobs, ({ many }) => ({
  requirements: many(jobs_requirements, {
            relationName: 'requirements',
    }),
      }))
export const relations_posts = relations(posts, ({ one }) => ({
  featuredImage: one(media, {
    
    fields: [posts.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
    }),
      }))
export const relations_applications = relations(applications, ({ one }) => ({
  position: one(jobs, {
    
    fields: [applications.position],
    references: [jobs.id],
    relationName: 'position',
    }),
    cv: one(media, {
    
    fields: [applications.cv],
    references: [media.id],
    relationName: 'cv',
    }),
      }))
export const relations_media_variants = relations(media_variants, ({ one }) => ({
  _parentID: one(media, {
    
    fields: [media_variants._parentID],
    references: [media.id],
    relationName: 'variants',
    }),
      }))
export const relations_media = relations(media, ({ many }) => ({
  variants: many(media_variants, {
            relationName: 'variants',
    }),
      }))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
    }),
      }))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
            relationName: 'sessions',
    }),
      }))
export const relations_payload_kv = relations(payload_kv, () => ({
  
      }))
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
  parent: one(payload_locked_documents, {
    
    fields: [payload_locked_documents_rels.parent],
    references: [payload_locked_documents.id],
    relationName: '_rels',
    }),
    jobsID: one(jobs, {
    
    fields: [payload_locked_documents_rels.jobsID],
    references: [jobs.id],
    relationName: 'jobs',
    }),
    postsID: one(posts, {
    
    fields: [payload_locked_documents_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
    }),
    applicationsID: one(applications, {
    
    fields: [payload_locked_documents_rels.applicationsID],
    references: [applications.id],
    relationName: 'applications',
    }),
    mediaID: one(media, {
    
    fields: [payload_locked_documents_rels.mediaID],
    references: [media.id],
    relationName: 'media',
    }),
    usersID: one(users, {
    
    fields: [payload_locked_documents_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
      }))
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
  _rels: many(payload_locked_documents_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
  parent: one(payload_preferences, {
    
    fields: [payload_preferences_rels.parent],
    references: [payload_preferences.id],
    relationName: '_rels',
    }),
    usersID: one(users, {
    
    fields: [payload_preferences_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
      }))
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_migrations = relations(payload_migrations, () => ({
  
      }))

type DatabaseSchema = {
  enum_jobs_category: typeof enum_jobs_category
  enum_jobs_type: typeof enum_jobs_type
  enum_jobs_tag: typeof enum_jobs_tag
  enum_jobs_status: typeof enum_jobs_status
  enum_posts_category: typeof enum_posts_category
  enum_applications_status: typeof enum_applications_status
  jobs_requirements: typeof jobs_requirements
  jobs: typeof jobs
  posts: typeof posts
  applications: typeof applications
  media_variants: typeof media_variants
  media: typeof media
  users_sessions: typeof users_sessions
  users: typeof users
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_jobs_requirements: typeof relations_jobs_requirements
  relations_jobs: typeof relations_jobs
  relations_posts: typeof relations_posts
  relations_applications: typeof relations_applications
  relations_media_variants: typeof relations_media_variants
  relations_media: typeof relations_media
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}
    

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
    