
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-d1-sqlite'
import { sqliteTable, index, uniqueIndex, foreignKey, integer, text, numeric } from '@payloadcms/db-d1-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-d1-sqlite/drizzle'

export const jobs_requirements = sqliteTable('jobs_requirements', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: text('id').primaryKey(),
  requirement: text('requirement').notNull(),
}, (columns) => [
    index('jobs_requirements_order_idx').on(columns._order), index('jobs_requirements_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [jobs.id],
      name: 'jobs_requirements_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const jobs = sqliteTable('jobs', {
  id: integer('id').primaryKey(),
  title: text('title').notNull(),
  slug: text('slug'),
  icon: text('icon').default("💼"),
  category: text('category', {enum: ['cong-nghe', 'kinh-doanh', 'marketing', 'van-hanh', 'nhan-su', 'tai-chinh']}),
  location: text('location'),
  type: text('type', {enum: ['full-time', 'part-time', 'contract', 'intern']}).default("full-time"),
  level: text('level', {enum: ['fresher', 'junior', 'middle', 'senior', 'manager']}),
  salary: text('salary'),
  tag: text('tag'),
  description: text('description', {mode: 'json'}),
  benefits: text('benefits', {mode: 'json'}),
  status: text('status', {enum: ['active', 'closed']}).default("active"),
  publishedAt: text('published_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    uniqueIndex('jobs_slug_idx').on(columns.slug), index('jobs_updated_at_idx').on(columns.updatedAt), index('jobs_created_at_idx').on(columns.createdAt),
]
)


export const posts = sqliteTable('posts', {
  id: integer('id').primaryKey(),
  title: text('title').notNull(),
  slug: text('slug'),
  category: text('category', {enum: ['su-kien', 'cong-nghe', 'van-hoa', 'kinh-doanh', 'van-hanh']}),
  excerpt: text('excerpt'),
  content: text('content', {mode: 'json'}),
  featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  externalImageUrl: text('external_image_url'),
  author: text('author'),
  readTime: text('read_time'),
  featured: integer('featured', {mode: 'boolean'}).default(false),
  publishedAt: text('published_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    uniqueIndex('posts_slug_idx').on(columns.slug), index('posts_featured_image_idx').on(columns.featuredImage), index('posts_updated_at_idx').on(columns.updatedAt), index('posts_created_at_idx').on(columns.createdAt),
]
)


export const applications = sqliteTable('applications', {
  id: integer('id').primaryKey(),
  fullName: text('full_name').notNull(),
  email: text('email').notNull(),
  phone: text('phone').notNull(),
  linkedIn: text('linked_in'),
  position: integer('position_id').references(() => jobs.id, {
      onDelete: 'set null'
  }),
  positionText: text('position_text'),
  experience: text('experience', {enum: ['0-1', '1-3', '3-5', '5-10', '10+']}),
  expectedSalary: text('expected_salary'),
  cv: integer('cv_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  coverLetter: text('cover_letter'),
  status: text('status', {enum: ['new', 'reviewing', 'accepted', 'rejected']}).default("new"),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('applications_position_idx').on(columns.position), index('applications_cv_idx').on(columns.cv), index('applications_updated_at_idx').on(columns.updatedAt), index('applications_created_at_idx').on(columns.createdAt),
]
)


export const media_variants = sqliteTable('media_variants', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: text('id').primaryKey(),
  name: text('name'),
  url: text('url'),
  width: numeric('width', {mode: 'number'}),
  height: numeric('height', {mode: 'number'}),
  fileSize: numeric('file_size', {mode: 'number'}),
}, (columns) => [
    index('media_variants_order_idx').on(columns._order), index('media_variants_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [media.id],
      name: 'media_variants_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const media = sqliteTable('media', {
  id: integer('id').primaryKey(),
  alt: text('alt'),
  originalFileSize: numeric('original_file_size', {mode: 'number'}),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  url: text('url'),
  thumbnailURL: text('thumbnail_u_r_l'),
  filename: text('filename'),
  mimeType: text('mime_type'),
  filesize: numeric('filesize', {mode: 'number'}),
  width: numeric('width', {mode: 'number'}),
  height: numeric('height', {mode: 'number'}),
  focalX: numeric('focal_x', {mode: 'number'}),
  focalY: numeric('focal_y', {mode: 'number'}),
  sizes_hero_url: text('sizes_hero_url'),
  sizes_hero_width: numeric('sizes_hero_width', {mode: 'number'}),
  sizes_hero_height: numeric('sizes_hero_height', {mode: 'number'}),
  sizes_hero_mimeType: text('sizes_hero_mime_type'),
  sizes_hero_filesize: numeric('sizes_hero_filesize', {mode: 'number'}),
  sizes_hero_filename: text('sizes_hero_filename'),
  sizes_large_url: text('sizes_large_url'),
  sizes_large_width: numeric('sizes_large_width', {mode: 'number'}),
  sizes_large_height: numeric('sizes_large_height', {mode: 'number'}),
  sizes_large_mimeType: text('sizes_large_mime_type'),
  sizes_large_filesize: numeric('sizes_large_filesize', {mode: 'number'}),
  sizes_large_filename: text('sizes_large_filename'),
  sizes_medium_url: text('sizes_medium_url'),
  sizes_medium_width: numeric('sizes_medium_width', {mode: 'number'}),
  sizes_medium_height: numeric('sizes_medium_height', {mode: 'number'}),
  sizes_medium_mimeType: text('sizes_medium_mime_type'),
  sizes_medium_filesize: numeric('sizes_medium_filesize', {mode: 'number'}),
  sizes_medium_filename: text('sizes_medium_filename'),
  sizes_thumb_url: text('sizes_thumb_url'),
  sizes_thumb_width: numeric('sizes_thumb_width', {mode: 'number'}),
  sizes_thumb_height: numeric('sizes_thumb_height', {mode: 'number'}),
  sizes_thumb_mimeType: text('sizes_thumb_mime_type'),
  sizes_thumb_filesize: numeric('sizes_thumb_filesize', {mode: 'number'}),
  sizes_thumb_filename: text('sizes_thumb_filename'),
}, (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt), index('media_created_at_idx').on(columns.createdAt), uniqueIndex('media_filename_idx').on(columns.filename), index('media_sizes_hero_sizes_hero_filename_idx').on(columns.sizes_hero_filename), index('media_sizes_large_sizes_large_filename_idx').on(columns.sizes_large_filename), index('media_sizes_medium_sizes_medium_filename_idx').on(columns.sizes_medium_filename), index('media_sizes_thumb_sizes_thumb_filename_idx').on(columns.sizes_thumb_filename),
]
)


export const users_sessions = sqliteTable('users_sessions', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: text('id').primaryKey(),
  createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  expiresAt: text('expires_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('users_sessions_order_idx').on(columns._order), index('users_sessions_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const users = sqliteTable('users', {
  id: integer('id').primaryKey(),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  email: text('email').notNull(),
  resetPasswordToken: text('reset_password_token'),
  resetPasswordExpiration: text('reset_password_expiration').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  salt: text('salt'),
  hash: text('hash'),
  loginAttempts: numeric('login_attempts', {mode: 'number'}).default(0),
  lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt), index('users_created_at_idx').on(columns.createdAt), uniqueIndex('users_email_idx').on(columns.email),
]
)


export const payload_kv = sqliteTable('payload_kv', {
  id: integer('id').primaryKey(),
  key: text('key').notNull(),
  data: text('data', {mode: 'json'}).notNull(),
}, (columns) => [
    uniqueIndex('payload_kv_key_idx').on(columns.key),
]
)


export const payload_locked_documents = sqliteTable('payload_locked_documents', {
  id: integer('id').primaryKey(),
  globalSlug: text('global_slug'),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug), index('payload_locked_documents_updated_at_idx').on(columns.updatedAt), index('payload_locked_documents_created_at_idx').on(columns.createdAt),
]
)


export const payload_locked_documents_rels = sqliteTable('payload_locked_documents_rels', {
  id: integer('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: text('path').notNull(),
  jobsID: integer('jobs_id'),
  postsID: integer('posts_id'),
  applicationsID: integer('applications_id'),
  mediaID: integer('media_id'),
  usersID: integer('users_id'),
}, (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order), index('payload_locked_documents_rels_parent_idx').on(columns.parent), index('payload_locked_documents_rels_path_idx').on(columns.path), index('payload_locked_documents_rels_jobs_id_idx').on(columns.jobsID), index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID), index('payload_locked_documents_rels_applications_id_idx').on(columns.applicationsID), index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID), index('payload_locked_documents_rels_users_id_idx').on(columns.usersID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['jobsID']],
      foreignColumns: [jobs.id],
      name: 'payload_locked_documents_rels_jobs_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['applicationsID']],
      foreignColumns: [applications.id],
      name: 'payload_locked_documents_rels_applications_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk'
    }).onDelete('cascade'),
]
)


export const payload_preferences = sqliteTable('payload_preferences', {
  id: integer('id').primaryKey(),
  key: text('key'),
  value: text('value', {mode: 'json'}),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('payload_preferences_key_idx').on(columns.key), index('payload_preferences_updated_at_idx').on(columns.updatedAt), index('payload_preferences_created_at_idx').on(columns.createdAt),
]
)


export const payload_preferences_rels = sqliteTable('payload_preferences_rels', {
  id: integer('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: text('path').notNull(),
  usersID: integer('users_id'),
}, (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order), index('payload_preferences_rels_parent_idx').on(columns.parent), index('payload_preferences_rels_path_idx').on(columns.path), index('payload_preferences_rels_users_id_idx').on(columns.usersID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk'
    }).onDelete('cascade'),
]
)


export const payload_migrations = sqliteTable('payload_migrations', {
  id: integer('id').primaryKey(),
  name: text('name'),
  batch: numeric('batch', {mode: 'number'}),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt), index('payload_migrations_created_at_idx').on(columns.createdAt),
]
)

export const relations_jobs_requirements = relations(jobs_requirements, ({ one }) => ({
  _parentID: one(jobs, {
    
    fields: [jobs_requirements._parentID],
    references: [jobs.id],
    relationName: 'requirements',
    }),
      }))
export const relations_jobs = relations(jobs, ({ many }) => ({
  requirements: many(jobs_requirements, {
            relationName: 'requirements',
    }),
      }))
export const relations_posts = relations(posts, ({ one }) => ({
  featuredImage: one(media, {
    
    fields: [posts.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
    }),
      }))
export const relations_applications = relations(applications, ({ one }) => ({
  position: one(jobs, {
    
    fields: [applications.position],
    references: [jobs.id],
    relationName: 'position',
    }),
    cv: one(media, {
    
    fields: [applications.cv],
    references: [media.id],
    relationName: 'cv',
    }),
      }))
export const relations_media_variants = relations(media_variants, ({ one }) => ({
  _parentID: one(media, {
    
    fields: [media_variants._parentID],
    references: [media.id],
    relationName: 'variants',
    }),
      }))
export const relations_media = relations(media, ({ many }) => ({
  variants: many(media_variants, {
            relationName: 'variants',
    }),
      }))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
    }),
      }))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
            relationName: 'sessions',
    }),
      }))
export const relations_payload_kv = relations(payload_kv, () => ({
  
      }))
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
  parent: one(payload_locked_documents, {
    
    fields: [payload_locked_documents_rels.parent],
    references: [payload_locked_documents.id],
    relationName: '_rels',
    }),
    jobsID: one(jobs, {
    
    fields: [payload_locked_documents_rels.jobsID],
    references: [jobs.id],
    relationName: 'jobs',
    }),
    postsID: one(posts, {
    
    fields: [payload_locked_documents_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
    }),
    applicationsID: one(applications, {
    
    fields: [payload_locked_documents_rels.applicationsID],
    references: [applications.id],
    relationName: 'applications',
    }),
    mediaID: one(media, {
    
    fields: [payload_locked_documents_rels.mediaID],
    references: [media.id],
    relationName: 'media',
    }),
    usersID: one(users, {
    
    fields: [payload_locked_documents_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
      }))
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
  _rels: many(payload_locked_documents_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
  parent: one(payload_preferences, {
    
    fields: [payload_preferences_rels.parent],
    references: [payload_preferences.id],
    relationName: '_rels',
    }),
    usersID: one(users, {
    
    fields: [payload_preferences_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
      }))
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_migrations = relations(payload_migrations, () => ({
  
      }))

type DatabaseSchema = {
  jobs_requirements: typeof jobs_requirements
  jobs: typeof jobs
  posts: typeof posts
  applications: typeof applications
  media_variants: typeof media_variants
  media: typeof media
  users_sessions: typeof users_sessions
  users: typeof users
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_jobs_requirements: typeof relations_jobs_requirements
  relations_jobs: typeof relations_jobs
  relations_posts: typeof relations_posts
  relations_applications: typeof relations_applications
  relations_media_variants: typeof relations_media_variants
  relations_media: typeof relations_media
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}
    

declare module '@payloadcms/db-d1-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
    